---
title: "metabolitesOverview"
author: "Pieter Clauw"
date: "08/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
source('../Functions/H.r')
knitr::opts_knit$set(root.dir = "/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/")
library(tidyverse)
library(kableExtra)
```

## Metabilite Overview
Exploration of the metabolite data of 250 accessions in two temperatures (16ºC and 6ºC),
within the scope of running GWAS analyses.
Both single trait and multitrait (both temperatures) will be run.


```{r Data, include = F}
dist.metabol <- read_csv('Data/Metabolites/metabolic_distance.csv')
dist.inner <- read_csv('Data/Metabolites/innerdistance.csv')
metabol.acn <- read_csv('Data/Metabolites/metabolites_accessions.csv')
metabol.sample <- read_csv('Data/Metabolites/metabolites.csv')
autumnTemp <- read_delim('../QandD2/Results/Growth/meanAutumnTemperatureCLusters.txt', '\t')
```

```{r datacleansing, include = F}
dist.metabol <- select(dist.metabol, accession, distance)
dist.inner <- rename(dist.inner, temperature = condition, distance = dist) %>% select(accession, temperature, distance)
metabol.acn <- select(metabol.acn, -(X1), temperature = condition) 
metabol.sample <- select(metabol.sample, -(X1), temperature = condition) %>% select(sample, accession, temperature, experiment, everything())
```

```{r general variables}
metabolites <- names(select(metabol.acn, -(c(accession, temperature))))
temperatures <- c('16C', '6C')
```
=


## Distributions
### metabolic distance
```{r metabol distance hist}
ggplot(dist.metabol, aes(distance)) +
  geom_histogram(bins = 100, fill = 'green', alpha = 0.5) +
  labs(x = 'metabolic distance', title = 'metabolic distance between 16ºC and 6ºC')

#ggplot(vegLengths, aes(length, fill = veg)) + 
   #geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')

```

### inner distance
```{r inner distance hist}
ggplot(dist.inner, aes(distance, fill = temperature)) +
  geom_histogram(bins = 100, alpha = 0.5, position = 'identity') +
  labs(x = 'metabolic distance', title = 'metabolic distance within each temperature')
```


### Metabolites
```{r metabolite hist}
for (metabol in metabolites)
{
  pdf(paste('Results/Metabolome/Plots/', metabol, 'histogram.pdf', sep = '_'))
   g <- ggplot(metabol.acn, aes_string(metabol, fill = "temperature")) +
    geom_histogram(bins = 100, alpha = 0.5, position = 'identity')
   print(g)
  dev.off()
}
```


## Heritabilities
```{r H of metabolites}
h <- metabol.sample %>%
  select(-experiment) %>%
  gather(key = 'metabolite', value = 'measurement', -sample, -accession, -temperature) %>%
  split(f = list(.$metabolite, .$temperature), sep = '_') %>%
  map(~H(as.data.frame(.[, c('accession', 'measurement')]), print = F)[4])

h <- h %>%
  as_tibble() %>%
  gather(key = 'metabol.temp', value = 'heritability') %>%
  separate(data = ., col = metabol.temp, into = c('metabolite', 'temperature'), sep = "_")

h %>%
  spread(key = temperature, value = heritability)
```


```{r write gwas data file(s)}
gwas.metabol <- metabol.acn %>%
  gather(key = 'metabolite', value = 'measurement', -accession, -temperature) %>%
  unite(col = 'metabol_temp', metabolite, temperature, sep = '_') %>%
  spread(key = metabol_temp, value = measurement)
write_csv(gwas.metabol,'Data/Metabolites/GWAS/metabolites.csv')

gwas.inner <- dist.inner %>%
  spread(key = temperature, value = distance) %>%
  rename(distance_16C = `16C`, distance_6C = `6C`)
write_csv(gwas.inner,'Data/Metabolites/GWAS/innerMetabolicDistance.csv')

write_csv(dist.metabol, 'Data/Metabolites/GWAS/metabolicDistance_16Cvs6C.csv')
```
## correlation mean autumn temperature
```{r}
#ToDo: recode to tidyverse
autumnTemp <- as.data.frame(autumnTemp)
autumnTemp$meanAutumn <- autumnTemp$meanAutumn
dist.metabol <- as.data.frame(dist.metabol)

dist.metabol$autumnTemp <- autumnTemp$meanAutumn[match(dist.metabol$accession, autumnTemp$acn)]

# Visuals
# temperatureRange
tempRange <- seq(-10, 20, by = 1)

# get plasma colours for temperature on continuous scale
autumnTemp$autumnTempInterval <- findInterval(autumnTemp$meanAutumn, tempRange)
autumnTempColours.cte <- plasma(length(tempRange))
autumnTemp$autumnTempCol <- autumnTempColours.cte[autumnTemp$autumnTempInterval]

# legend
autumnTemp.legend <- data.frame('autumnTemp' = tempRange, 'autumnTempCol' = NA)
autumnTemp.legend$autumnTempCol <- autumnTempColours.cte[c(1:length(tempRange))]

# colours
dist.metabol$autumnTempCol <- autumnTemp$autumnTempCol[match(dist.metabol$accession, autumnTemp$acn)]

pdf('Results/Metabolome/Plots/metabolicDistance_vs_autumnTemperature.pdf', useDingbats = FALSE)
plot(dist.metabol$autumnTemp, dist.metabol$distance, col = dist.metabol$autumnTempCol, xlab = expression(paste('autumn temperature (',degree~C,')')), pch = 19, ylab = expression(paste('metabolic distance (16',degree~C,'vs. 6',degree~C,')')), cex.axis = 1.3, cex.lab = 1.3, xlim = c(-6, 20), xaxs = 'i')
     
abline(lm(dist.metabol$distance ~ dist.metabol$autumnTemp))
ct <- cor.test(dist.metabol$autumnTemp, dist.metabol$distance)
text(x = par('usr')[1], y = par('usr')[4], paste('p: ', format.pval(ct$p.value, digits = 3, eps = 0.0001, nsmall = 4), sep = '' ), adj = c(-0.25 ,1.25))
text(x = par('usr')[1], y = par('usr')[4], paste('r: ', round(ct$estimate, 4), sep = '' ), adj = c(-0.275 ,2.75))
gradientLegend(valRange = autumnTemp.legend$autumnTemp, color = autumnTemp.legend$autumnTempCol, pos = 0.5 - (2.25/30), length = 30/26, side = 1, inside = T, pos.num = 3, n.seg = 1, coords = F, depth = 0.01)
dev.off()
```


