---
title: "growthOverview"
author: "Pieter Clauw"
date: "13/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
source('Rfunctions.R')
library(nlme)
```


```{r data}
# estimated marginal means fron mixed nmodel
growth <- read.table('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/lemna_DAS_allReps_NO_logRosette_emmeans_V3_CorCAR1_correct.txt', header = T)
lemna <- read.table('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Data/Growth/rawdata_combined_annotation_NO.txt', header = T, sep = '\t')
autumnTemp <- read.table('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/QandD2/Results/Growth/meanAutumnTemperatureCLusters.txt', head = T)
```
```{r general variables}
accessions <- unique(growth$acn)
temperatures <- unique(growth$temp)
minDAS <- min(growth$DAS)
maxDAS <- max(growth$DAS)

# TODO: replace by legend in 'autumn temperature'
autumnTempClust_Col <- data.frame(autumnTempClust = unique(growth$autumnTempClust), autumnTempCol = NA)
autumnTempClust_Col$autumnTempCol <- growth$autumnTempCol[match(autumnTempClust_Col$autumnTempClust, growth$autumnTempClust)]
autumnTempClust_Col <- autumnTempClust_Col[order(autumnTempClust_Col$autumnTempClust), ]

```

```{r autumn temperature}
autumnTempColours <- rainbow(6, s = 0.8, v = 1, start = 0.05, end = 0.78)
growth$autumnTempClust <- autumnTemp$tmeanAutumnClustTemp[match(growth$acn, autumnTemp$acn)]
growth$autumnTempClust <- factor(growth$autumnTempClust, levels = c('4C', '7C', '9C', '11C', '13C', '17C'), ordered = T)
growth$autumnTempCol <- autumnTempColours[growth$autumnTempClust]
growth$autumnTemp <- autumnTemp$meanAutumn[match(growth$acn, autumnTemp$acn)]/10

legend.df <- data.frame('cluster' = sort(unique(growth$autumnTempClust)), 'col' = NA)
legend.df$col <- growth$autumnTempCol[match(legend.df$cluster, growth$autumnTempClust)]
```


## Model fit
Raw data versus model estimates
```{r model fit}
lemna$Area[lemna$Area == 0] <- NA
lemna$logArea <- log(lemna$Area)
for (a in accessions)
{
  pdf(paste('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/Plots/ModelFit_poly3_logRosette_NO_allReps_V3_corCAR1/logRosetteOverTime_acn_', a, '.pdf', sep =''), width = 14)
  minDAS <- min(lemna$DAS, na.rm = T)
  maxDAS <- max(lemna$DAS, na.rm = T)
  minArea <- min(lemna$logArea, na.rm = T)
  maxArea <- max(lemna$logArea, na.rm = T)
  temperatures <- as.character(unique(lemna$temp))
  repeats <- unique(lemna$rep)
  blueTransp <- rgb(0,0,1, alpha = 0.6)
  redTransp <- rgb(1,0,0, alpha = 0.6)
  tempcol <- data.frame('temp' = as.character(na.omit(temperatures)), 'col' = c('blue', 'red'), 'transpCol' = c(blueTransp, redTransp))
  tempcol$col <- as.character(tempcol$col)
  tempcol$transpCol <- as.character(tempcol$transpCol)
  repPch <- data.frame('rep' = as.character(na.omit(repeats)), 'pch' = c(1, 0, 2))
 
  plot(NA,NA, xlim = c(minDAS, maxDAS), ylim = c(minArea, maxArea), main = a, xlab = 'DAS', ylab = 'logArea')
  legend.txt <- c('rep1', 'rep2', 'rep3', '6C', '16C')
  legend.pch <- c(1, 0, 2, NA, NA)
  legend.col <- c('black', 'black', 'black', 'blue', 'red')
  legend.lwd <- c(NA, NA, NA, 3, 3)
  legend('topleft', legend = legend.txt, pch = legend.pch, col = legend.col, lwd = legend.lwd, ncol = 2)
  

  
  for (t in temperatures)
  {
    clr <- tempcol$col[tempcol$temp == t]
    transpClr <- tempcol$transpCol[tempcol$temp == t]
    lemna.a.t <- lemna[lemna$acn == a & lemna$temperature == t, ]
    lemna.a.t$pch <- repPch$pch[match(lemna.a.t$rep, repPch$rep)]
    growth.a.t <- growth[growth$acn == a & growth$temp == t, ]
    polX <- c(growth.a.t$DAS, rev(growth.a.t$DAS))
    polY <- c((growth.a.t$emmean + growth.a.t$SE), (rev(growth.a.t$emmean) - rev(growth.a.t$SE)))
    
    lines(growth.a.t$DAS, growth.a.t$emmean, col = clr, lwd = 3)
    polygon(x = polX, y = polY, col = transpClr, border = NA)
    points(lemna.a.t$DAS, lemna.a.t$logArea, col = clr, pch = lemna.a.t$pch, cex = 0.7)
  }
  dev.off()
}

```
Visually, the model is fitting the data very well.
Only accession 8343 is showing a very weird growth distinction between 6ºC and 16ºC.


## Growth over time


```{r rosette area over time 16vs6C}
minArea <- min(growth$emmean)
maxArea <- max(growth$emmean)
for (t in temperatures)
{
  pdf(paste('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/Plots/logArea_overtime_tempclustCol_', t, '.pdf', sep = ''), height = 5, width = 14)
  plot(NA, NA, xlim = c(minDAS, maxDAS), ylim = c(minArea, maxArea), xlab = 'DAS (days after stratification)', ylab = 'log(rosette area)')
  for (a in accessions)
  {
    growth.t.a <- growth[growth$temp == t & growth$acn == a, ]
    col = unique(growth.t.a$autumnTempCol)
    lines(growth.t.a$DAS, growth.t.a$emmean, col = col)
  }
  legend('topleft', legend = autumnTempClust_Col$autumnTempClust, col = autumnTempClust_Col$autumnTempCol, lty = 1, bty = 'n')
  dev.off()
}
```



## Linear growth rates (LGR)
```{r LGR 14-35DAS}
getSlope.14.35 <- function(acn, temp)
{
  getSlope(acn, temp, DAS1 = 14, DAS2 = 35, emm = growth)
}
```

```{r calculate LGR}
LGR <- data.frame(acn = rep(accessions, length(temperatures)), temp = rep(temperatures, each = length(accessions)))
LGR$slope <- mapply(LGR$acn, LGR$temp, FUN = getSlope.14.35)
LGR$autumnTempCol <- growth$autumnTempCol[match(LGR$acn, growth$acn)]
LGR$autmnTemp <- autumnTemp$meanAutumn[match(LGR$acn, autumnTemp$acn)]/10
```



## Response curves

## correlation with autumn temperature
### LGR at 6C and 16C
```{r LGR autumnTemp}
for (t in temperatures)
{
  LGR.t <- LGR[LGR$temp == t, ]
  pdf(paste('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/Plots/linearGrowth_14_35DAS', t, 'autumnTemperature.pdf', sep = '_'))
  plot(LGR.t$autmnTemp, LGR.t$slope, col = LGR.t$autumnTempCol, xlab = expression(paste('autumn temperature (',degree~C,')')), pch = 19, ylab = 'growth rate (14-35DAS)', cex.axis = 1.3, cex.lab = 1.3)
  abline(lm(LGR.t$slope ~ LGR.t$autmnTemp))
  ct <- cor.test(LGR.t$autmnTemp, LGR.t$slope)
  text(x = par('usr')[1], y = par('usr')[4], paste('p: ', format.pval(ct$p.value, digits = 3, eps = 0.0001, nsmall = 4), sep = '' ), adj = c(-0.25 ,1.25))
  text(x = par('usr')[1], y = par('usr')[4], paste('r: ', round(ct$estimate, 4), sep = '' ), adj = c(-0.275 ,2.75))
  dev.off()
}
```

### LGR response curve
```{r plot LGR response curve}
minSlope <- min(LGR$slope)
maxSlope <- max(LGR$slope)
pdf(paste('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/Plots/linearGrowth_14_35DAS_responsecurve.pdf', sep = ''))
plot(NA, NA, xlim = c(0.5, 2.5), ylim = c(minSlope, maxSlope), xaxt = 'n', xlab = '', ylab = ' growth rate (14-35DAS)', cex.axis = 1.2, cex.lab = 1.2)
for (acn in unique(LGR$acn))
{
  LGR.a <- LGR[LGR$acn == acn, ]
  LGR.a$temp <- factor(LGR.a$temp, levels = c('16C', '6C'), ordered = T)
  points(LGR.a$temp, LGR.a$slope, col = LGR.a$autumnTempCol)
  lines(LGR.a$temp, LGR.a$slope, col = LGR.a$autumnTempCol)
}
legend('topright', legend = legend.df$cluster, col = legend.df$col, pch = rep(1, 6), bty = 'n', ncol = 2)
axis(side = 1, at = c(1, 2), labels = c('16C', '6C'), cex.axis = 1.2)
dev.off()
```
```{r calculate LGR response slope}
LGR.respCurve <- data.frame('acn' = accessions, respCurve = NA)
LGR.respCurve$respCurve <- unlist(lapply(LGR.respCurve$acn, FUN = getRespCurve, growthSlopes = LGR))
LGR.respCurve$autumnTemp <- autumnTemp$meanAutumn[match(LGR.respCurve$acn, autumnTemp$acn)]/10
LGR.respCurve$autumnTempCol <- growth$autumnTempCol[match(LGR.respCurve$acn, growth$acn)]
```

```{r LGR response slope vs autumn temperature}
pdf(paste('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/Plots/linearGrowth_14_35DAS_responseslope_VS_autumnTemperature.pdf', sep = ''))
plot(LGR.respCurve$autumnTemp, LGR.respCurve$respCurve, col = LGR.respCurve$autumnTempCol, xlab = expression(paste('autumn temperature (',degree~C,')')), pch = 19, ylab = 'response slope', cex.axis = 1.3, cex.lab = 1.3)
  abline(lm(LGR.respCurve$respCurve ~ LGR.respCurve$autumnTemp))
  ct <- cor.test(LGR.respCurve$autumnTemp, LGR.respCurve$respCurve)
  text(x = par('usr')[1], y = par('usr')[4], paste('p: ', format.pval(ct$p.value, digits = 3, eps = 0.0001, nsmall = 4), sep = '' ), adj = c(-0.25 ,1.25))
  text(x = par('usr')[1], y = par('usr')[4], paste('r: ', round(ct$estimate, 4), sep = '' ), adj = c(-0.275 ,2.75))
  dev.off()
```


```{r write data for GWAS}

```


