---
title: "Heritabilities"
author: "Pieter Clauw"
date: "19/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
source('Rfunctions.R')
source('../Functions/H.r')
library(nlme)

```

```{r data}
# estimated marginal means fron mixed nmodel
lemna <- read.table('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Data/Growth/rawdata_combined_annotation_NO.txt', header = T, sep = '\t')
# load the mixed model
load("/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/poly3_logRosette_NO_allReps_V3_corCAR1_correct.rda")
# randomisation Files
randomFiles <- list.files('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Setup/GrowthChamber/', pattern = 'chamberRandomisation_.*_rep', full.names = T)
randomisations <- lapply(randomFiles, FUN = read.table, header = T, stringsAsFactors = F)
names(randomisations) <- c('16C_rep1', '16C_rep2', '16C_rep3', '6C_rep1', '6C_rep2', '6C_rep3')


```

```{r general variables}
acns_rep1 <- unique(lemna$acn[lemna$rep == 'rep1'])
acns_rep2 <- unique(lemna$acn[lemna$rep == 'rep2'])
acns_rep3 <- unique(lemna$acn[lemna$rep == 'rep3'])
accessions <- intersect(intersect(acns_rep2, acns_rep3), acns_rep1)

DASs <- c(14:35)
experiments <- unique(lemna$experiment)
temperatures <- unique(lemna$temperature)
replicates <- unique(lemna$replicate)
# replicates conmbined with over all replicates (pseudo-replicate called 'overall')
replicates.h <- c(replicates, 'overall')

dataTypes <- c('raw', 'predicted')
```
```{r visuals}
tempCol <- c('blue', 'red')
repPch <- c(15:18)
repType <- c('b', 'b', 'b', 'l')
visTempRep <- data.frame('temperature' = rep(temperatures, each = length(replicates.h)), 'replicate' = rep(replicates.h, length(temperatures)), 'tempCol' = rep(tempCol, each = length(replicates.h)), 'repPch' = rep(repPch, length(temperatures)), repType = rep(repType, length(temperatures)))

visPredRaw <- data.frame('data' = dataTypes, 'lty' = c(1:2))

```


```{r prepare data}
lemna$Area[lemna$Area == 0] <- NA
lemna$logArea <- log(lemna$Area)
```



```{r model predictions}
# prepare newdata for prediction
predictDataFrames <- lapply(experiments, FUN = predictData.PerExperiment)
predictData <- do.call(rbind, predictDataFrames)
predictData$acn <- as.factor(as.character(predictData$acn))
# predict
predictData$logArea <- predict(lemnaSlim.poly, newdata = predictData)

# add meta info
predictData$replicate <- unlist(lapply(predictData$experiment, function(exp){strsplit(exp, split = '_')[[1]][2]}))
```


## Heritabilities 
#### Rosette area
broad-sense heritabilities of rosette area of raw data and individual predictions from the linear mixed model
```{r calculate heritabilities}
# dataframes to store heritbailities based on raw data and predicted data respectively
h <- list()
for (dt in dataTypes)
{
  h[[dt]] <- data.frame('DAS' = rep(DASs, length(temperatures) * length(replicates.h)), 'temperature' =  rep(temperatures, each = length(DASs) * length(replicates.h)), 'replicate' = rep(rep(replicates.h, each = length(DASs)), length(temperatures)), 'H' = NA, stringsAsFactors = F)
}

for (dt in dataTypes)
{
  for (rep in replicates.h)
  {  
    data.r <- NULL
    if (dt == 'raw'){data.r <- lemna}
    else if (dt == 'predicted'){data.r <- predictData}
    # select specific replicate data if necessary
    if (rep != 'overall')
    {
      data.r <- data.r[data.r$replicate == rep, ]
    }
    for (t in temperatures)
    {
      for (DAS in DASs)
      {
        data.r.t.d <- data.r[data.r$temperature == t & data.r$DAS == DAS, c('acn', 'logArea')]
        if (nrow(data.r.t.d) == 0){h[[dt]]$H[h[[dt]]$DAS == DAS & h[[dt]]$temperature == t & h[[dt]]$replicate == rep] <- NA}
        else {h[[dt]]$H[h[[dt]]$DAS == DAS & h[[dt]]$temperature == t & h[[dt]]$replicate == rep] <- H(data.r.t.d, print = F)[4]}
      }
    }
  }
}

```
```{r plot heritabilities}
for (dt in dataTypes)
{
  minH <- min(h[[dt]]$H, na.rm = T)
  maxH <- max(h[[dt]]$H, na.rm = T)
  pdf(paste('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/Plots/heritbailities_', dt, '.pdf', sep = ''), useDingbats = F, width = 14)
  par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
  plot(NA,NA, xlim = c(DASs[1], DASs[length(DASs)]), ylim = c(minH, maxH), xlab = 'days after stratification (DAS)', ylab = 'broad sense heritability', main = dt)
  for (t in temperatures)
  {
    for (rep in replicates.h)
    {
      # select H for given temperature and replicate
      h.t.r <- h[[dt]][h[[dt]]$temperature == t & h[[dt]]$replicate == rep, ]
      # plot properties
      col <- visTempRep$tempCol[visTempRep$temperature == t]
      pch <- visTempRep$repPch[visTempRep$replicate == rep]
      type <- unique(visTempRep$repType[visTempRep$replicate == rep])
      #plot lines
      lines(h.t.r$DAS, h.t.r$H, col = col, pch = pch, type = type)
      # legend
      legend('topright', inset=c(-0.25,0), legend = c(temperatures, replicates.h), col = c(tempCol, rep('black', length(replicates.h))), pch = c(NA,NA, repPch[1:3], NA), lty = c(1,1, NA, NA, NA, 1))
    }
  }
  dev.off()
}

```





### Linear growth rates







