---
title: "nonlinear_bayesian_zscore"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
library(tidyverse)
library(brms)
library(ggpubr)
knitr::opts_knit$set(root.dir = "/groups/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/")
```


```{r data}
lemna <- read_delim('Data/Growth/rawdata_combined_annotation_NO.txt', delim = '\t')
linear_params <- read_csv('Results/Growth/nonlinear/modelParameters.csv')
```
```{r preparation}
# data preparation #
lemna$ID <- paste(lemna$pot, lemna$experiment, sep = '_')
lemna$acn <- as.character(lemna$acn)
lemna$Area[lemna$Area == 0] <- NA

# only use accessions which have data for all replicates
acns_rep1 <- unique(lemna$acn[lemna$replicate == 'rep1'])
acns_rep2 <- unique(lemna$acn[lemna$replicate == 'rep2'])
acns_rep3 <- unique(lemna$acn[lemna$replicate == 'rep3'])

acns_rep123 <- intersect(intersect(acns_rep2, acns_rep3), acns_rep1)
lemna <- lemna[lemna$acn %in% acns_rep123, ]

# subset #
lemna.sub <- lemna %>%
  drop_na(Area) %>%
  mutate(
         ID,
         acn = as.factor(acn),
         experiment = as.factor(experiment),
         temperature = as.factor(temperature),
         replicate = as.factor(replicate),
         DAS_decimal = DAS_decimal - 14,
         DAS = floor(DAS_decimal),
         Area) %>%
  select(ID, acn, experiment, temperature, replicate, DAS_decimal, DAS, Area)


# Area transformations
mean.t0 <- mean(lemna.sub$Area[lemna.sub$DAS == 0])
sd.t0 <- sd(lemna.sub$Area[lemna.sub$DAS == 0])
lemna.sub <- lemna.sub %>%
  mutate(
    Area.M0z = (Area - mean.t0)/sd.t0,
    Area.2000px = (Area/2000)
  )

lemna.16C <- filter(lemna.sub, temperature == '16C')
lemna.6C <- filter(lemna.sub, temperature == '6C')
```


```{r fit_16C_acns.a}
# new priors
mean(lemna.sub$Area[lemna.sub$DAS == 0])
sd(lemna.sub$Area[lemna.sub$DAS == 0])


prior.16C.M0 <- prior(normal(1866.112, 1048.961), nlpar = 'M0')
prior.16C.r <- prior(normal(0.5, 0.5), nlpar = 'r', lb = 0)
prior.16C.beta <- prior(normal(0.9, 0.1), nlpar = 'beta', lb = 0)


fit_16C_acns.a <- brm(
  bf(Area ~ (M0^(1 - beta) + r * DAS_decimal * (1 - beta))^(1 / (1 - beta)),
     M0 ~ 1, r ~ 1, beta ~ 1,
     nl = T),
  data = lemna.16C,
  prior = c(
    prior.16C.M0,
    prior.16C.r,
    prior.16C.beta),
  cores = 4
  )

save(fit_16C_acns.a, file = '/groups/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit_16C_acns.a.rda')

summary(fit_16C_acns.a)
plot(fit_16C_acns.a, ask = F)
plot(conditional_effects(fit_16C_acns.a), points = TRUE)
```


```{r fit_16C_acns.b}
# new priors
mean(lemna.sub$Area[lemna.sub$DAS == 0])
sd(lemna.sub$Area[lemna.sub$DAS == 0])


prior.16C.M0 <- prior(normal(0, 1), nlpar = 'M0')
prior.16C.r <- prior(normal(0.5, 0.5), nlpar = 'r', lb = 0)
prior.16C.beta <- prior(normal(0.9, 0.1), nlpar = 'beta', lb = 0)


fit_16C_acns.b <- brm(
  bf(Area.M0z ~ (M0^(1 - beta) + r * DAS_decimal * (1 - beta))^(1 / (1 - beta)),
     M0 ~ 1, r ~ 1, beta ~ 1,
     nl = T),
  data = lemna.16C,
  prior = c(
    prior.16C.M0,
    prior.16C.r,
    prior.16C.beta),
  cores = 4
  )

save(fit_16C_acns.b, file = '/groups/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit_16C_acns.b.rda')

summary(fit_16C_acns.b)
plot(fit_16C_acns.b, ask =F)
plot(conditional_effects(fit_16C_acns.b), points = TRUE)
```

```{r fit_16C_acns.c}
# new priors
mean(lemna.sub$Area[lemna.sub$DAS == 0])
sd(lemna.sub$Area[lemna.sub$DAS == 0])


prior.16C.M0 <- prior(normal(1.8, 1), nlpar = 'M0')
prior.16C.r <- prior(normal(0.5, 0.5), nlpar = 'r', lb = 0)
prior.16C.beta <- prior(normal(0.9, 0.1), nlpar = 'beta', lb = 0)


fit_16C_acns.c <- brm(
  bf(Area.2000px ~ (M0^(1 - beta) + r * DAS_decimal * (1 - beta))^(1 / (1 - beta)),
     M0 ~ 1, r ~ 1, beta ~ 1,
     nl = T),
  data = lemna.16C,
  prior = c(
    prior.16C.M0,
    prior.16C.r,
    prior.16C.beta),
  cores = 4
  )

save(fit_16C_acns.c, file = '/groups/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit_16C_acns.c.rda')

summary(fit_16C_acn.c)
plot(fit_16C_acn.c)
plot(conditional_effects(fit_16C_acn.c), points = TRUE)
```


```{r fit_16C_acns.d}
# new priors
mean(lemna.16C$Area.2000px[lemna.16C$DAS == 0], na.rm = T)
sd(lemna.16C$Area.2000px[lemna.16C$DAS == 0], na.rm = T)


prior.16C.M0 <- prior(normal(0.80, 0.44), nlpar = 'M0', lb = 0)
prior.16C.r <- prior(normal(0.5, 0.5), nlpar = 'r', lb = 0)
prior.16C.beta <- prior(normal(0.9, 0.1), nlpar = 'beta', lb = 0.5)


fit_16C_acns.d <- brm(
  bf(Area.2000px ~ (M0^(1 - beta) + r * DAS_decimal * (1 - beta))^(1 / (1 - beta)),
     M0 ~ 1, r ~ 1, beta ~ 1,
     nl = T),
  data = lemna.16C,
  prior = c(
    prior.16C.M0,
    prior.16C.r,
    prior.16C.beta),
  cores = 4
  )

save(fit_16C_acns.d, file = '/groups/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit_16C_acns.d.rda')

summary(fit_16C_acns.d)
plot(fit_16C_acns.d)
plot(conditional_effects(fit_16C_acns.d), points = TRUE)
```


```{r}
lemna.16C.t0 <- lemna.16C[lemna.16C$DAS == 0, ]

fit_M0 <- lm(Area.2000px ~ acn, data = lemna.16C.t0)
summary(fit_M0)

prior.16C.M0 <- prior(normal(0.80, 0.44), nlpar = 'M0', lb = 0)
prior.16C.r <- prior(normal(0.5, 0.5), nlpar = 'r', lb = 0)
prior.16C.beta <- prior(normal(0.9, 0.1), nlpar = 'beta', lb = 0.5)

median(lemna.16C.t0$Area.2000px)
sd(lemna.16C.t0$Area.2000px)

prior.16C.M0 <- set_prior(normal())



bprior <- set_prior(normal(0.70, 0.44), nlpar = 'M0', coef = Intercept) +
set_prior(normal(0.11, 0.08), nlpar = 'M0') +
set_prior(normal(0.5, 0.5), nlpar = 'r', coef = Intercept) +
set_prior(normal(0, 0.5), nlpar = 'r') +
set_prior(normal(0.8, 0.1), nlpar = 'beta')

cprior <- prior(normal(0.80, 0.44), nlpar = 'M0', lb = 0) +
  prior(normal(0.5, 0.5), nlpar = 'r', lb = 0) +
  prior(normal(0.9, 0.1), nlpar = 'beta', lb = 0.5)

fit_16C_acns.e <- brm(
  bf(Area.2000px ~ (M0^(1 - beta) + r * DAS_decimal * (1 - beta))^(1 / (1 - beta)),
     M0 ~ acn, r ~ acn, beta ~ 1,
     nl = T),
  data = lemna.16C,
  prior = cprior,
  cores = 4
  )


```





