---
title: "nonlinear_mixedmodel_temperatureSplit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
library(tidyverse)
library(nlme)
library(ggpubr)
knitr::opts_knit$set(root.dir = "/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/")
```


```{r data}
lemna <- read_delim('Data/Growth/rawdata_combined_annotation_NO.txt', delim = '\t')
```
```{r function}
# self-starting nonlinear power law function in R
# Written by C. Scherber, 4th December 2013
# http://www.christoph-scherber.de/self-starting%20power%20law%20function.txt

# Please acknowledge me should you use this function in publications.
# note that response and explanatory variables need to be strictly positive.

powermodel=function(x,a,b,c)
{a+b*x^c}

powermodelInit=function(mCall,LHS,data){
    xy=sortedXyData(mCall[["x"]],LHS,data)
    lmFit1=lm(xy[,"y"]~1) #for "intercept", a
    lmFit2=lm(log(xy[,"y"])~log(xy[,"x"])) #for b and c
    coefs1=coef(lmFit1)
    coefs2=coef(lmFit2)
    a=coefs1
    b=exp(coefs2[1])
    c=coefs2[2]
    value=c(a,b,c)
    names(value)=mCall[c("a","b","c")]
    value
}

SSpower=selfStart(powermodel,powermodelInit,c("a","b","c"))


## self start function from ecology paper
# Self-start function for power-law fit. This self-start for this model is not provided by Pinhero and Bates (2000), so I wrote one. Unfortunately, it often does not lead to convergence. Any suggestions would be welcome
fmla.pow <- as.formula("~(M0^(1-beta) + r*x*(1-beta))^(1/(1-beta))")
Init.pow <- function(mCall, LHS, data){
    xy <- sortedXyData(mCall[["x"]], LHS, data)
    if(nrow(xy) < 4) {stop("Too few distinct x values to fit a power-law")}
	r    <-coef(lm(log(y) ~ x, xy))[2]    # Use the slope from a log fit to the data as an initial guess for r
	M0   <- min(xy$y)		              # Use the minimum y value as an initial guess for M0
	beta <- 0.9	                          # give initial guess of beta as 0.9. don't use beta = 1, as it's undefined (1/0)
    value <- c(M0, r, beta) 
    names(value) <- mCall[c("M0", "r", "beta")]
 	return(value)
	}
SS.pow  <- selfStart(fmla.pow, initial = Init.pow, parameters = c("M0", "r", "beta"))



```
```{r data preparation}
lemna$ID <- paste(lemna$pot, lemna$experiment, sep = '_')
lemna$acn <- as.character(lemna$acn)
lemna$Area[lemna$Area == 0] <- NA

# only use accessions which have data for all replicates
acns_rep1 <- unique(lemna$acn[lemna$replicate == 'rep1'])
acns_rep2 <- unique(lemna$acn[lemna$replicate == 'rep2'])
acns_rep3 <- unique(lemna$acn[lemna$replicate == 'rep3'])

acns_rep123 <- intersect(intersect(acns_rep2, acns_rep3), acns_rep1)
lemna <- lemna[lemna$acn %in% acns_rep123, ]
```

```{r subset}
acns.nr <- 249
rep.nr <- 3
temp.nr <- 2

lemna.sub <- lemna %>%
  filter(acn %in% unique(lemna$acn)[1:acns.nr], replicate %in% unique(lemna$replicate)[1:rep.nr], temperature %in% unique(lemna$temperature)[1:temp.nr]) %>%
  drop_na(Area) %>%
  select(ID, acn, experiment, temperature, replicate, DAS_decimal, Area) %>%
  mutate(DAS = round(DAS_decimal),
         ID = as.factor(ID),
         acn = as.factor(acn),
         temperature = as.factor(temperature),
         replicate = as.factor(replicate),
         experiment = as.factor(experiment))

lemna.sub.split <- lemna.sub %>%
  group_split(temperature, replicate)
```

```{r nls}
ctrl <- nls.control(maxiter = 1000, warnOnly = T)
# power function
fm1.nls.pow.16 <- nls(Area ~ SSpower(DAS_decimal, a, b ,c), data = lemna.sub.split[[1]], control = ctrl)
fm1.nls.pow.6 <- nls(Area ~ SSpower(DAS_decimal, a, b ,c), data = lemna.sub.split[[2]], control = ctrl)

#fpl
fm1.nls.fpl.16 <- nls(Area ~ SSfpl(DAS_decimal, A, B, xmid, scal), data = lemna.sub.split[[1]], control = ctrl)
fm1.nls.fpl.6 <- nls(Area ~ SSfpl(DAS_decimal, A, B, xmid, scal), data = lemna.sub.split[[2]], control = ctrl)


p.pow.16 <- plot(fm1.nls.pow.16, main = 'fm1.nls.pow.16')
p.pow.6 <- plot(fm1.nls.pow.6, main = 'fm1.nls.pow.6')
p.fpl.16 <- plot(fm1.nls.fpl.16, main = 'fm1.nls.fpl.16')
p.fpl.6 <- plot(fm1.nls.fpl.6, main = 'fm1.nls.fpl.6')
ggarrange(p.pow.16, p.pow.6, p.fpl.16, p.fpl.6)
```

```{r nlsList}
# power function
fm.lis.pow.16 <- nlsList(Area ~ SSpower(DAS, a, b, c) | acn,
                         data = lemna.sub.split[[1]],
                         control = ctrl)

fm.lis.pow.6 <- nlsList(Area ~ SSpower(DAS, a, b, c) | acn,
                         data = lemna.sub.split[[2]],
                         control = ctrl)
# fpl
fm.lis.fpl.16 <- nlsList(Area ~ SSfpl(DAS, A, B, xmid, scal) | acn,
                      data = lemna.sub.split[[1]],
                      control = ctrl)

fm.lis.fpl.6 <- nlsList(Area ~ SSfpl(DAS, A, B, xmid, scal) | acn,
                      data = lemna.sub.split[[2]],
                      control = ctrl)

# plot
p.pow.16 <- plot(fm.lis.pow.16, main = 'fm.lis.pow.16')
p.pow.6 <- plot(fm.lis.pow.6, main = 'fm.lis.pow.6')
p.fpl.16 <- plot(fm.lis.fpl.16, main = 'fm.lis.fpl.16')
p.fpl.6 <- plot(fm.lis.fpl.6, main = 'fm.lis.fpl.6')
ggarrange(p.pow.16, p.pow.6, p.fpl.16, p.fpl.6)
```

```{r nlme}
ctrl <- nlmeControl(msMaxIter = 1000, maxIter = 1000, opt = 'nlminb')

fm1.nlme.pow.16 <- nlme(fm.lis.pow.16,
                      groups = ~ acn,
                      control = ctrl,
                      verbose = T)

fm1.nlme.pow.6 <- nlme(fm.lis.pow.6,
                      groups = ~ acn,
                      control = ctrl,
                      verbose = T)


fm1.nlme.fpl.16 <- nlme(fm.lis.fpl.16,
                      groups = ~ acn,
                      control = ctrl,
                      verbose = T)

fm1.nlme.fpl.6 <- nlme(fm.lis.fpl.6,
                      groups = ~ acn,
                      control = ctrl,
                      verbose = T)

```

```{r fit per experiment - power function 1}
ctrl.nls <- nls.control(maxiter = 1000, warnOnly = T)
ctrl.nlme <- nlmeControl(maxIter = 5000, msMaxIter = 100000, opt = 'nlminb')

model.nlme.pow <- function(data)
{
  fit.lis <- nlsList(Area ~ SSpower(DAS_decimal, a, b, c) | ID,
                         data = data,
                         control = ctrl.nls)
  fit.nlme <- nlme(fit.lis,
              control = ctrl.nlme,
              data = data,
              verbose = T)
  return(fit.nlme)
}

fit.nlme.pow <- lapply(lemna.sub.split, model.nlme.pow)

# 1 does not converge - 16C rep1
fit.nlme.pow.1 <- model.nlme.pow(lemna.sub.split[[1]])
# due to highly unbalanced data over time?
# take only DAS 16:30

# 2 does converge - 16C rep2
fit.nlme.pow.2 <- model.nlme.pow(lemna.sub.split[[2]])
save(fit.nlme.pow.2, file = 'Data/Growth/fit.nlme.pow.2.rda')
load('Data/Growth/fit.nlme.pow.2.rda')
# 3 does converge - 16C rep3
fit.nlme.pow.3 <- model.nlme.pow(lemna.sub.split[[3]])
save(fit.nlme.pow.3, file = 'Data/Growth/fit.nlme.pow.3.rda')
load('Data/Growth/fit.nlme.pow.3.rda')
# 4 does not converge - 6C rep1
# did converge on cluster (R version 3.6.2) with 16 cores
# converges with ID as grouping
fit.nlme.pow.4 <- model.nlme.pow(lemna.sub.split[[4]])
load('Data/Growth/fit.nlme.pow.4.rda')
# 5 does converge - 6C rep2 (50 iterations) with acn as grouping
fit.nlme.pow.5 <- model.nlme.pow(lemna.sub.split[[5]])
save(fit.nlme.pow.5, file = 'Data/Growth/fit.nlme.pow.5.rda')
load('Data/Growth/fit.nlme.pow.5.rda')
# 6 does  converge - 6C rep3 (10 iterations)
fit.nlme.pow.6 <- model.nlme.pow(lemna.sub.split[[6]])
save(fit.nlme.pow.6, file = 'Data/Growth/fit.nlme.pow.6.rda')
load('Data/Growth/fit.nlme.pow.6.rda')
```
```{r fit per experiment - power function eco}
ctrl.nls <- nls.control(maxiter = 1000, warnOnly = T)
ctrl.nlme <- nlmeControl(maxIter = 5000, msMaxIter = 100000, opt = 'nlminb')

model.nlme.poweco <- function(data)
{
  fit.lis <- nlsList(Area ~ SS.pow(DAS_decimal, M0, r, beta) | ID,
                         data = data,
                         control = ctrl.nls)
  fit.nlme <- nlme(fit.lis,
              control = ctrl.nlme,
              data = data,
              verbose = T)
  return(fit.nlme)
}


# convergence improves when using DAS_decimal instead of DAS

# 1 no convergence - 16C_rep1
fit.nlme.poweco.1 <- model.nlme.poweco(lemna.sub.split[[1]])

# 2 no convergence - 16C rep2
fit.nlme.poweco.2 <- model.nlme.poweco(lemna.sub.split[[2]])
save(fit.nlme.poweco.2, file = 'Data/Growth/fit.nlme.poweco.2.rda')
load('Data/Growth/fit.nlme.poweco.2.rda')
# 3  no convergence - 16C rep3
fit.nlme.poweco.3 <- model.nlme.poweco(lemna.sub.split[[3]])
save(fit.nlme.poweco.3, file = 'Data/Growth/fit.nlme.poweco.3.rda')
load('Data/Growth/fit.nlme.poweco.3.rda')
# 4 no convergence - 6C rep1 (only converges with acn as grouping)
fit.nlme.poweco.4 <- model.nlme.poweco(lemna.sub.split[[4]])
save(fit.nlme.poweco.4, file = 'Data/Growth/fit.nlme.poweco.4.rda')
load('Data/Growth/fit.nlme.poweco.4.rda')
# 5 convergence - 6C rep2 
fit.nlme.poweco.5 <- model.nlme.poweco(lemna.sub.split[[5]])
save(fit.nlme.poweco.5, file = 'Data/Growth/fit.nlme.poweco.5.rda')
load('Data/Growth/fit.nlme.poweco.5.rda')
# 6 convergence - 6C rep3 
fit.nlme.poweco.6 <- model.nlme.poweco(lemna.sub.split[[6]])
save(fit.nlme.poweco.6, file = 'Data/Growth/fit.nlme.poweco.6.rda')
load('Data/Growth/fit.nlme.poweco.6.rda')
```

```{r 6C}
ctrl.nls <- nls.control(maxiter = 1000, warnOnly = T)
ctrl.nlme <- nlmeControl(maxIter = 5000, msMaxIter = 100000, opt = 'nlminb')
lemna.6C <- rbind(lemna.sub.split[[4]], lemna.sub.split[[5]], lemna.sub.split[[6]])
lemna.6C$DAS_decimal <- lemna.6C$DAS_decimal - 14

fit.lis.6C <- nlsList(Area ~ SS.pow(DAS_decimal, M0, r, beta) | acn,
                     data = lemna.6C,
                     control = ctrl.nls)

n.acns <- length(unique(lemna.6C$acn)) -1
start.6C <- c(fixef(fit.lis.6C)[1], rep(0, n.acns), fixef(fit.lis.6C)[2], rep(0, n.acns), fixef(fit.lis.6C)[3], rep(0, n.acns))

# CONVERGES
fit2.nlme.6C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = M0 + r + beta ~ 1,
                    groups = ~ acn,
                    start = fixef(fit.lis.6C),
                    random = pdDiag(M0 ~ replicate),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2.nlme.6C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit2.nlme.6C.rda')

start.6C <- c(fixef(fit2.nlme.6C)[1], rep(0, n.acns), fixef(fit2.nlme.6C)[2], rep(0, n.acns), fixef(fit2.nlme.6C)[3], rep(0, n.acns))
# CONVERGES #
fit3.nlme.6C <- update(fit2.nlme.6C,
                    fixed = list(M0 ~ acn, r + beta ~ 1),
                    groups = ~ acn,
                    start = c(fixef(fit2.nlme.6C)[1], rep(0, n.acns), fixef(fit2.nlme.6C)[2], fixef(fit2.nlme.6C)[3]),
                    random = pdDiag(list(M0 ~ replicate)),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit3.nlme.6C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit3.nlme.6C.rda')
# CONVERGES
fit4.nlme.6C <- update(fit3.nlme.6C,
                    fixed = list(M0 + r ~ acn, beta ~ 1),
                    groups = ~ acn,
                    start = c(fixef(fit3.nlme.6C)[1:249], fixef(fit3.nlme.6C)[250], rep(0, n.acns), fixef(fit3.nlme.6C)[251]),
                    random = pdDiag(list(M0 ~ replicate)),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit4.nlme.6C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit4.nlme.6C.rda')
# THE MODEL
fit5.nlme.6C <- update(fit4.nlme.6C,
                    fixed = list(M0 + r ~ acn, beta ~ 1),
                    groups = ~ ID,
                    start = fixef(fit4.nlme.6C),
                    random = pdDiag(list(M0 ~ replicate)),
                    correlation = corCAR1(form =  ~ DAS_decimal),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit5.nlme.6C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit5.nlme.6C.rda')

# extend random effects
fit5b.nlme.6C <- update(fit5.nlme.6C,
                    fixed = list(M0 + r ~ acn, beta ~ 1),
                    groups = ~ ID,
                    start = fixef(fit5.nlme.6C),
                    random = pdDiag(list(M0 ~ replicate, r ~ 1, beta ~ 1)),
                    correlation = corCAR1(form =  ~ DAS_decimal),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)

# NO CONVERGENCE
fit7.nlme <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 + r ~ acn, beta ~ 1),
                    groups = ~ ID,
                    start = c(fixef(fit.lis.6C)[1], rep(0, n.acns), fixef(fit.lis.6C)[2], rep(0, n.acns), fixef(fit.lis.6C)[3]),
                    random = pdDiag(list(M0 ~ replicate)),
                    correlation = corCAR1(form =  ~ DAS_decimal),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)


pdf('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/augPred_fit5_6C.pdf')
for(acn in accessions)
{
  predData.a <- predData %>%
    filter(acn == !!acn) %>%
    mutate(DAS_decimal = DAS_decimal + 14)
  
  lemna.16C.a <- lemna.16C %>%
    filter(acn == !!acn) %>%
    mutate(DAS_decimal = DAS_decimal + 14)
  
  print(ggplot(predData.a, aes(DAS_decimal, fit2f)) +
    geom_line() +
    geom_point(data = lemna.16C.a, aes(DAS_decimal, Area, group = replicate)))
}
dev.off()


# predict
DAS_decimal_pred <- c(0:21)
accessions <- unique(lemna.16C$acn)
predData <- data.frame(
  acn = rep(accessions, each = length(DAS_decimal_pred)),
  DAS_decimal= rep(DAS_decimal_pred, length(accessions)))

predData$fit2f <- predict(fit2f.nlme.16C, newdata = predData, level = 0)


# plot raw data
pdf('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/dataPlots/rawData_6C_perAcn.pdf')
for (acn in unique(lemna.6C$acn))
{
  lemna.6C.a <- filter(lemna.6C, acn == !!acn)
  p <- ggplot(lemna.6C.a, aes(DAS_decimal, Area, colour = replicate)) +
    geom_line(aes(group = ID)) +
    ggtitle(acn)
  print(p)
}
dev.off()


```
```{r 6C updated after 16C}
ctrl.nls <- nls.control(maxiter = 1000, warnOnly = T)
ctrl.nlme <- nlmeControl(maxIter = 5000, msMaxIter = 100000, opt = 'nlminb')
lemna.6C <- rbind(lemna.sub.split[[4]], lemna.sub.split[[5]], lemna.sub.split[[6]])

lemna.6C$DAS_decimal <- lemna.6C$DAS_decimal - 14
n.acns <- length(unique(lemna.6C$acn)) - 1

fit.lis.6C <- nlsList(Area ~ SS.pow(DAS_decimal, M0, r, beta) | acn,
                     data = lemna.6C,
                     control = ctrl.nls)


# CONVERGES
fit2.nlme.6C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ 1, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(median(coef(fit.lis.6C)$M0), median(coef(fit.lis.6C)$r), median(coef(fit.lis.6C)$beta)),
                    random = pdBlocked(list(M0 ~ 1, r ~ 1, beta ~ 1)),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2.nlme.6C, file = '~/Documents/GMI/fit2.nlme.6C.rda')
# CONVERGES
fit2b.nlme.6C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ acn, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(fixef(fit2.nlme.6C)[1], rep(0, n.acns), fixef(fit2.nlme.6C)[2], fixef(fit2.nlme.6C)[3]),
                    random = pdBlocked(list(M0 ~ 1, r ~ 1, beta ~1)),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2b.nlme.6C, file = '~/Documents/GMI/fit2b.nlme.6C.rda')

# CONVERGES
fit2c.nlme.6C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ acn, r ~ acn, beta ~1),
                    groups = ~ acn,
                    start = c(fixef(fit2b.nlme.6C)[1:249], fixef(fit2b.nlme.6C)[250], rep(0, n.acns), fixef(fit2b.nlme.6C)[251]),
                    random = pdBlocked(list(M0 ~ 1, r ~ 1, beta ~1)),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2c.nlme.6C, file = '~/Documents/GMI/fit2c.nlme.6C.rda')

fit2d.nlme.6C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ acn, r ~ acn, beta ~1),
                    groups = ~ ID,
                    start = fixef(fit2c.nlme.6C),
                    correlation = corCAR1(form = ~ DAS_decimal),
                    random = pdBlocked(list(M0 ~ 1, r ~ 1)),
                    data = lemna.6C,
                    control = ctrl.nlme,
                    verbose = T)


```


```{r 16C}
ctrl.nls <- nls.control(maxiter = 1000, warnOnly = T)
ctrl.nlme <- nlmeControl(maxIter = 5000, msMaxIter = 100000, opt = 'nlminb')
lemna.16C <- rbind(lemna.sub.split[[1]], lemna.sub.split[[2]], lemna.sub.split[[3]])
lemna.16C <- lemna.16C[lemna.16C$DAS < 30, ]
lemna.16C$DAS_decimal <- lemna.16C$DAS_decimal - 14
n.acns <- length(unique(lemna.16C$acn)) - 1
# remove outlier in accession 5865
#lemna.16C <- lemna.16C[lemna.16C$ID != 'B.3_b6_16C_rep3', ]
#lemna.16C <- lemna.16C[lemna.16C$ID != 'A.7_a1_16C_rep3', ]

fit.lis.16C <- nlsList(Area ~ SS.pow(DAS_decimal, M0, r, beta) | acn,
                     data = lemna.16C,
                     control = ctrl.nls)
fit.lis.16C.coef <- coef(fit.lis.16C)
fit.lis.16C.coef[is.na(fit.lis.16C.coef)] <- 0

# CONVERGENCE
fit2.nlme.16C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ acn, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(fixef(fit.lis.16C)[1],fixef(fit.lis.16C)[2], fit.lis.16C.coef$r[-1], fixef(fit.lis.16C)[3]),
                    random = pdBlocked(list(M0 ~ replicate, r ~ 1, beta ~1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2.nlme.16C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit2.nlme.16C.rda')

# CONVERGES, better than fit2
fit2b.nlme.16C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ acn, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(median(coef(fit.lis.16C)$M0, na.rm = T), rep(0, n.acns), median(coef(fit.lis.16C)$r, na.rm = T), median(coef(fit.lis.16C)$beta, na.rm = T)),
                    random = pdBlocked(list(M0 ~ 1, r ~ 1, beta ~1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2b.nlme.16C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit2b.nlme.16C.rda')
# CONVERGES, better model (anova)
fit2c.nlme.16C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ acn, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(median(coef(fit.lis.16C)$M0, na.rm = T), rep(0, n.acns), median(coef(fit.lis.16C)$r, na.rm = T), median(coef(fit.lis.16C)$beta, na.rm = T)),
                    random = pdBlocked(list(M0 ~ replicate, r ~ 1, beta ~1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2c.nlme.16C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit2c.nlme.16C.rda')
# unclear whether it would converge, probabaly not
fit2d.nlme.16C <- update(fit2c.nlme.16C,
                    fixed = list(M0 ~ acn, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(median(coef(fit.lis.16C)$M0, na.rm = T), rep(0, n.acns), median(coef(fit.lis.16C)$r, na.rm = T), median(coef(fit.lis.16C)$beta, na.rm = T)),
                    random = pdBlocked(list(M0 ~ replicate, r ~ replicate, beta ~1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)
# CONVERGES!
fit2e.nlme.16C <- update(fit2c.nlme.16C,
                    fixed = list(M0 ~ acn, r ~ acn, beta ~1),
                    groups = ~ acn,
                    start = c(fixef(fit2c.nlme.16C)[1:249], fixef(fit2c.nlme.16C)[250], rep(0, n.acns), fixef(fit2c.nlme.16C)[251]),
                    random = pdBlocked(list(M0 ~ replicate, r ~ 1, beta ~1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2e.nlme.16C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit2e.nlme.16C.rda')
# CONVERGES
fit2f.nlme.16C <- update(fit2e.nlme.16C,
                    fixed = list(M0 ~ acn, r ~ acn, beta ~1),
                    groups = ~ ID,
                    start = fixef(fit2e.nlme.16C),
                    random = pdBlocked(list(M0 ~ replicate, r ~ 1, beta ~1)),
                    correlation = corCAR1(form = ~ DAS_decimal),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)
save(fit2f.nlme.16C, file = '/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/fit2f.nlme.16C.rda')





# use model estimates to extend model with extra timepoint
lemna.16C <- rbind(lemna.sub.split[[1]], lemna.sub.split[[2]], lemna.sub.split[[3]])
lemna.16C$DAS_decimal <- lemna.16C$DAS_decimal - 14

# model does not converge with full dataset, probably to unbalanced between replicates (replicate one only has data until 30DAS)
# visually, the model with the data until 30DAS sufficiently models also the data until 35DAS.
fit2g.nlme.16C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = list(M0 ~ acn, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(fixef(fit2f.nlme.16C)[1:249], fixef(fit2f.nlme.16C)[250], fixef(fit2f.nlme.16C)[499]),
                    random = pdBlocked(list(M0 ~ replicate, r ~ 1, beta ~1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)

# plot to see if model on limited data is sufficient
DAS_decimal_pred <- c(0:21)
accessions <- unique(lemna.16C$acn)
predData <- data.frame(
  acn = rep(accessions, each = length(DAS_decimal_pred)),
  DAS_decimal= rep(DAS_decimal_pred, length(accessions)))

predData$fit2f <- predict(fit2f.nlme.16C, newdata = predData, level = 0)

pdf('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/augPred_fit2f_16C.pdf')
for(acn in accessions)
{
  predData.a <- predData %>%
    filter(acn == !!acn) %>%
    mutate(DAS_decimal = DAS_decimal + 14)
  
  lemna.16C.a <- lemna.16C %>%
    filter(acn == !!acn) %>%
    mutate(DAS_decimal = DAS_decimal + 14)
  
  print(ggplot(predData.a, aes(DAS_decimal, fit2f)) +
    geom_line() +
    geom_point(data = lemna.16C.a, aes(DAS_decimal, Area, group = replicate)))
  
}
dev.off()





fit3.nlme.16C <- update(fit2.nlme.16C,
                    fixed = list(M0 ~ acn, r ~ 1, beta ~1),
                    groups = ~ acn,
                    start = c(fixef(fit2.nlme.16C)[1:249],fixef(fit2.nlme.16C)[250], fixef(fit2.nlme.16C)[251]),
                    random = pdBlocked(list(M0 ~ replicate, r ~ replicate, beta ~1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)




fit.lis.16C <- nlsList(Area ~ SSlogis(DAS_decimal, Asym, xmid, scal) | ID,
                     data = lemna.16C,
                     control = ctrl.nls)
# CONVERGES
fit.nlme.16C <- nlme(fit.lis.16C,
                     control = ctrl.nlme,
                     verbose = T)

fit2.nlme.16C <- update(fit.nlme.16C,
                        fixed = list(Asym ~ acn, xmid + scal ~ 1),
                        groups = ~ acn,
                        start = c(fixef(fit.nlme.16C)[1], rep(0, n.acns), fixef(fit.nlme.16C)[2], fixef(fit.nlme.16C)[3]),
                        random = Asym ~ replicate,
                        data = lemna.16C,
                        control = ctrl.nlme,
                        verbose = T)




n.acns <- length(unique(lemna.16C$acn)) - 1
fit2b.nlme.16C <- nlme(Area ~ SSlogis(DAS_decimal, Asym, xmid, scal),
                       fixed = list(Asym ~ acn, xmid + scal ~ 1),
                        groups = ~ acn,
                        start = c(fixef(fit.lis.16C)[1], rep(0, n.acns), fixef(fit.lis.16C)[2], fixef(fit.lis.16C)[3]),
                        random = Asym ~ replicate,
                        data = lemna.16C,
                        control = ctrl.nlme,
                        verbose = T)

fit3.nlme.16C <- update(fit2b.nlme.16C,
                        fixed = list(Asym + scal ~ acn, xmid ~ 1),
                        groups = ~ acn,
                        start = c(fixef(fit2b.nlme.16C)[1:249], fixef(fit2b.nlme.16C)[250], rep(0, n.acns), fixef(fit2b.nlme.16C)[251]),
                        random = Asym + scal ~ replicate,
                        data = lemna.16C,
                        control = ctrl.nlme,
                        verbose = T)

fit3.nlme.16C <- update(fit2.nlme.16C,
                        fixed = list(Asym + xmid ~ acn, scal ~ 1),
                        groups = ~ acn,
                        start = c(fixef(fit2.nlme.16C)[1:249], fixef(fit2.nlme.16C)[250], rep(0, n.acns), fixef(fit2.nlme.16C)[251]),
                        random = pdDiag(Asym + xmid ~ replicate),
                        data = lemna.16C,
                        control = ctrl.nlme,
                        verbose = T)
# GOMPERTZ
fit.lis.gom.16C <- nlsList(Area ~ SSgompertz(DAS_decimal, Asym, b2, b3) | acn,
                     data = lemna.16C,
                     control = ctrl.nls)

# CONVERGENCEs with acn as group, not ID]
fit.nlme.gom.16C <- nlme(fit.lis.gom.16C,
                     control = ctrl.nlme,
                     verbose = T)

n.acns <- length(unique(lemna.16C$acn)) - 1

fit2.nlme.gom.16C <- update(fit.nlme.gom.16C,
                        fixed = list(b2 ~ acn, Asym + b3 ~ 1),
                        groups = ~ acn,
                        start = c(fixef(fit.nlme.gom.16C)[1], fixef(fit.nlme.gom.16C)[2], rep(0, n.acns), fixef(fit.nlme.gom.16C)[3]),
                        data = lemna.16C,
                        control = ctrl.nlme,
                        verbose = T)

# plot
fit.nlme.16C.predict <- predict(fit.nlme.gom.16C)
pdf('/Volumes/nordborg/user/pieter.clauw/Documents/Experiments/UltimateQandD/Results/Growth/nonlinear/dataPlots/rawData_16C_perAcn.pdf')
for (acn in sort(unique(lemna.16C$acn)))
{
  lemna.16C.a <- filter(lemna.16C, acn == !!acn)
  acn.emm <- fit.nlme.16C.predict[names(fit.nlme.16C.predict) == acn] 
  p <- ggplot(lemna.16C.a, aes(DAS_decimal, Area, colour = replicate)) +
    geom_line(aes(group = ID)) +
    ggtitle(acn)
  print(p)
}
dev.off()

# NO CONVERGENCE
fit2.nlme.16C <- nlme(Area ~ SSlogis(DAS_decimal, Asym, xmid, scal),
                    fixed = Asym + xmid + scal ~ 1,
                    groups = ~ acn,
                    start = fixef(fit.lis.16C),
                    random = pdDiag(scal ~ replicate),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)


fit2b.nlme.16C <- nlme(Area ~ SS.pow(DAS_decimal, M0, r, beta),
                    fixed = M0 + r + beta ~ acn,
                    groups = ~ acn,
                    start = c(fixef(fit.lis.16C)[1], rep(0, n.acns), fixef(fit.lis.16C)[2], rep(0,n.acns), fixef(fit.lis.16C)[3], rep(0, n.acns)),
                    random = pdBlocked(list(M0 ~ replicate, beta ~ 1, r ~ 1)),
                    data = lemna.16C,
                    control = ctrl.nlme,
                    verbose = T)


```


```{r fit per experiment - logis}
ctrl.nls <- nls.control(maxiter = 1000, warnOnly = T)
ctrl.nlme <- nlmeControl(maxIter = 5000, msMaxIter = 100000, opt = 'nlminb')

model.nlme.logis <- function(data)
{
  fit.lis <- nlsList(Area ~ SSlogis(DAS_decimal, Asym, xmid, scal) | ID,
                         data = data,
                         control = ctrl.nls)
  fit.nlme <- nlme(fit.lis,
              control = ctrl.nlme,
              data = data,
              verbose = T)
  return(fit.nlme)
}

# convergence improves when using DAS_decimal instead of DAS

# 1 convergence - 16C_rep1
fit.nlme.logis.1 <- model.nlme.logis(lemna.sub.split[[1]])
# take only completee data (DAS 16: 30)
# convergenc e(with DAS_decimal and ID as grouping)
lemna.sub.16C_rep1.sub <- filter(lemna.sub.split[[1]], DAS %in% c(16:30))
fit.nlme.logis.1.sub <- model.nlme.logis(lemna.sub.16C_rep1.sub)
# 2 convergence - 16C rep2 (104 iterations) with acn as grouping
fit.nlme.logis.2 <- model.nlme.logis(lemna.sub.split[[2]])
save(fit.nlme.logis.2, file = 'Data/Growth/fit.nlme.logis.2.rda')
load('Data/Growth/fit.nlme.logis.2.rda')
# 3 convergence - 16C rep3 (16 iterations) with acn as grouping
fit.nlme.logis.3 <- model.nlme.logis(lemna.sub.split[[3]])
save(fit.nlme.logis.3, file = 'Data/Growth/fit.nlme.logis.3.rda')
load('Data/Growth/fit.nlme.logis.3.rda')
# 4 no convergence  - 6C rep1
fit.nlme.logis.4 <- model.nlme.logis(lemna.sub.split[[4]])
save(fit.nlme.logis.4, file = 'Data/Growth/fit.nlme.logis.4.rda')
load('Data/Growth/fit.nlme.logis.4.rda')
# 5 no convergence - 6C rep2 
fit.nlme.logis.5 <- model.nlme.logis(lemna.sub.split[[5]])
save(fit.nlme.logis.5, file = 'Data/Growth/fit.nlme.logis.5.rda')
load('Data/Growth/fit.nlme.logis.5.rda')
# 6 convergence - 6C rep3 
fit.nlme.logis.6 <- model.nlme.logis(lemna.sub.split[[6]])
save(fit.nlme.logis.6, file = 'Data/Growth/fit.nlme.logis.6.rda')
load('Data/Growth/fit.nlme.logis.6.rda')
```
```{r fit per experiment - fpl}
ctrl.nls <- nls.control(maxiter = 1000, warnOnly = T)
ctrl.nlme <- nlmeControl(maxIter = 5000, msMaxIter = 100000, opt = 'nlminb')

model.nlme.fpl <- function(data)
{
  fit.lis <- nlsList(Area ~ SSfpl(DAS, A, B, xmid, scal) | acn,
                         data = data,
                         control = ctrl.nls)
  fit.nlme <- nlme(fit.lis,
              control = ctrl.nlme,
              data = data,
              verbose = T)
  return(fit.nlme)
}

# convergence improves when using DAS_decimal instead of DAS?

# 1 - 16C_rep1
fit.nlme.fpl.1 <- model.nlme.fpl(lemna.sub.split[[1]])

# 2 no convergence - 16C rep2 
fit.nlme.fpl.2 <- model.nlme.fpl(lemna.sub.split[[2]])
save(fit.nlme.fpl.2, file = 'Data/Growth/fit.nlme.fpl.2.rda')
load('Data/Growth/fit.nlme.fpl.2.rda')
# 3  - 16C rep3
fit.nlme.fpl.3 <- model.nlme.fpl(lemna.sub.split[[3]])
save(fit.nlme.fpl.3, file = 'Data/Growth/fit.nlme.fpl.3.rda')
load('Data/Growth/fit.nlme.fpl.3.rda')
# 4   - 6C rep1
fit.nlme.fpl.4 <- model.nlme.fpl(lemna.sub.split[[4]])
save(fit.nlme.fpl.4, file = 'Data/Growth/fit.nlme.fpl.4.rda')
load('Data/Growth/fit.nlme.fpl.4.rda')
# 5  - 6C rep2 
fit.nlme.fpl.5 <- model.nlme.fpl(lemna.sub.split[[5]])
save(fit.nlme.fpl.5, file = 'Data/Growth/fit.nlme.fpl.5.rda')
load('Data/Growth/fit.nlme.fpl.5.rda')
# 6  - 6C rep3 
fit.nlme.fpl.6 <- model.nlme.fpl(lemna.sub.split[[6]])
save(fit.nlme.fpl.6, file = 'Data/Growth/fit.nlme.fpl.6.rda')
load('Data/Growth/fit.nlme.fpl.6.rda')
```

```{r per temperature power function eco}
lemna.sub.6C <- rbind(lemna.sub.split[[1]], lemna.sub.split[[2]], lemna.sub.split[[3]])

model.nlme.test <- function(data)
{
  fit.lis <- nlsList(Area ~ SS.pow(DAS, M0, r, beta) | ID,
                         data = data,
                         control = ctrl.nls)
  fit.nlme <- nlme(fit.lis,
              control = ctrl.nlme,
              data = data,
              verbose = T)
  return(fit.nlme)
}

# model only runs when rep1 is excluded.
# What is so different about rep1 -> more or less outliers removed? check variances and means per accessino/ID.s
# also works with grouping by acn?
# replicate is random effect


fit.nlme.poweco.6C <- model.nlme.test(lemna.sub.6C)

# fixed effects
fit.nlme.poweco.6C.FE <- fixef(fit.nlme.poweco.6C)
n.acn <- length(unique(lemna.sub.6C$acn)) - 1 
start.6 = c(fit.nlme.poweco.6C.FE[1], rep(0, n.acn), fit.nlme.poweco.6C.FE[2], rep(0, n.acn), fit.nlme.poweco.6C.FE[3], rep(0, n.acn)) 

fit2.nlme.poweco.6C <- update(fit.nlme.poweco.6C,
                              data = lemna.sub.6C,
                              fixed = list(M0 + r + beta ~ acn),
                              start = start.6,
                              control = ctrl.nlme)
```



```{r get the fixed effects right}
# fixed effect with accession
fit.nlme.pow.6.FE <- fixef(fit.nlme.pow.6)
n.acn <- length(unique(lemna.sub.split[[6]]$acn)) - 1 
start.6 = c(fit.nlme.pow.6.FE[1], rep(0, n.acn), fit.nlme.pow.6.FE[2], rep(0, n.acn), fit.nlme.pow.6.FE[3], rep(0, n.acn)) 
fit2.nlme.pow.6 <- update(fit.nlme.pow.6,
                          data = lemna.sub.split[[6]],
                          fixed = list(a + b + c ~ acn),
                          start = start.6,
                          verbose = T)
# anova

# check coefficients for random effects





```

```{r get structure right for combining replicates}

```


